//page for individual sermon

import SanctuaryMenu from "@/components/layout/SanctuaryMenu";
import { getSermonById } from "@/utils/firebaseConfig";
import { getBibleStudyById, getBibleStudyLessons } from "@/utils/supabase";
import { Box, Card, CardContent, Grid, Tab, Tabs, Typography } from "@mui/material";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Markdown from 'react-markdown';

export default function SermonPage() {
  const router = useRouter();
  const [study_id, setStudyId] = useState<any>(router.query); // Get the study_id from the URL parameters
  const [study, setStudy] = useState<any>(null); // Initialize study state
  const [lessons, setLessons] = useState<any[]>([]); // Initialize lessons state
  const [currentLesson, setCurrentLesson] = useState<any>(null); // Initialize current lesson state

  useEffect(() => {
    if (!router.isReady) return; // Ensure the router is ready before accessing query parameters
    const { study_id } = router.query; // Get the study_id from the URL parameters
    getBibleStudyById(study_id as string).then((e) => {
      console.log(e);
      setStudy(e);
      if (e == null) return;
      getBibleStudyLessons(study_id as string).then((lessons) => {
        console.log(lessons);
        if (!lessons) {
          setLessons([]);
          setCurrentLesson(null); // No lessons available
          return;
        }
        setCurrentLesson(lessons[0]?.lesson_id || null); // Set the first lesson as current
        if (lessons) {
          setLessons(lessons);
        }
      });
    });

  }, [study_id, router.isReady]);

  return (
    <>
      <Head>
        <title>Sanctuary App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SanctuaryMenu />
      <div className="study-page" style={{ marginLeft: '240px', padding: '20px' }}>
        {study ? (
          <>
            <Card>
              <CardContent>
                <h1>{study.title}</h1>
                <p>{study.subtitle}</p>
              </CardContent>

            </Card>

            {lessons.length > 0 && currentLesson &&
              <>
                <Card>
                  <CardContent>
                    <h2>Lessons</h2>
                    <Tabs value={currentLesson} onChange={(e, newValue) => setCurrentLesson(newValue)} variant="scrollable" scrollButtons="auto">
                      {lessons.map((lesson) => (
                        <Tab value={lesson.lesson_id} label={"Lesson " + lesson.lesson_number} key={lesson.lesson_id} />
                      ))}
                    </Tabs>
                  </CardContent>
                </Card>
                <Grid container spacing={2} >
                  <Grid size={8}>
                    <Card >
                      <CardContent>
                        <h2>{lessons.find(lesson => lesson.lesson_id === currentLesson)?.title}</h2>
                        <p><h4 style={{color:"#8a9a5b"}}>Background Scripture:</h4> {(() => {
                          const scripture = lessons.find(lesson => lesson.lesson_id === currentLesson)?.scripture;
                          if(scripture.indexOf('[') === 0 && scripture.indexOf(']') === scripture.length - 1) {
                            // If scripture is an array in string format, parse it
                          const parsedScripture = JSON.parse(scripture);

                          if (Array.isArray(parsedScripture)) {
                            return parsedScripture.join(', ');
                          }
                        }
                          return scripture;
                        })()}</p>
                        <Markdown>{lessons.find(lesson => lesson.lesson_id === currentLesson)?.commentary}</Markdown>
                      </CardContent>
                    </Card>
                    
                  </Grid>
                  <Grid size={4}>
                    <Card style={{borderLeft: '4px solid #8A9A5B'}}>
                      <CardContent>
                        <h2 style={{fontWeight:600}}>Discussion Starters</h2>
                        <ul style={{ listStyleType: 'disc', paddingLeft: '20px' }}>
                          {lessons.find(lesson => lesson.lesson_id === currentLesson)?.discussion_starters?.map((starter: string, index: number) => (
                            <li key={index}>{starter}</li>
                          ))}
                        </ul>
                      </CardContent>
                    </Card>
                    <Card style={{borderLeft: '4px solid #8A9A5B', marginTop: '20px'}}>
                      <CardContent>
                        <h2 style={{fontWeight:600}}>{lessons.find(lesson => lesson.lesson_id === currentLesson)?.application_sidebar.title}</h2>
                        <p>{lessons.find(lesson => lesson.lesson_id === currentLesson)?.application_sidebar.body}</p>
                      </CardContent>
                      </Card>
                      
                    <Card style={{borderLeft: '4px solid #8A9A5B', marginTop: '20px'}}>
                      <CardContent>
                        <h2 style={{fontWeight:600}}>Summary</h2>
                        <p>{lessons.find(lesson => lesson.lesson_id === currentLesson)?.conclusion.summary}</p>
                      </CardContent>
                    </Card>
                    <Card style={{borderLeft: '4px solid #8A9A5B', marginTop: '20px'}}>
                      <CardContent>
                        <h2 style={{fontWeight:600}}>Remember...</h2>
                        <p>{lessons.find(lesson => lesson.lesson_id === currentLesson)?.conclusion.thoughtToRemember}</p>
                      </CardContent>
                    </Card>
                    <Card style={{borderLeft: '4px solid #8A9A5B', marginTop: '20px'}}>
                      <CardContent>
                        <h2 style={{fontWeight:600}}>Prayer</h2>
                        <p>{lessons.find(lesson => lesson.lesson_id === currentLesson)?.conclusion.prayer}</p>
                      </CardContent>
                    </Card>
                  </Grid>
                </Grid>
              </>
            }
          </>
        ) : (
          <p>Loading...</p>
        )}
      </div>
    </>
  )
}