import Head from "next/head";
import Image from "next/image";
import { AppBar, Box, Drawer, ThemeProvider, Toolbar } from "@mui/material";
import sanctuaryTheme from "@/styles/sanctuaryTheme";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { supabase } from '@/lib/supabaseClient';



export default function Home() {
  const router = useRouter();
  const [authenticated, setAuthenticated] = useState(false);

  useEffect(() => {
    
    const checkAuth = async () => {
      const { data: { user } } = await supabase.auth.getUser();
      console.log(user);
      if (!user) {
        router.push('/login'); // Redirect to login if not authenticated
      } else {
        setAuthenticated(true);
      }
    };
    checkAuth();
  }, [router]);

  if (!authenticated) return null; // Prevent rendering until authentication is checked

  return (
<>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar position="fixed">
          <Toolbar variant="dense" disableGutters></Toolbar>
        </AppBar>
        <Drawer className="dashboard-menu" variant="permanent" anchor="left" open={true}>
          <Box sx={{ width: 240}}>
            <Toolbar className="logo-area" sx={{backgroundColor:'#8CB4D4', boxShadow:3, paddingLeft:'1rem'}} variant="dense" disableGutters>
              <Image
                src="/sanctuary_logo.png"
                alt="Sanctuary Logo"
                width={28}
                height={28}
              /> 
              <span>Sanctuary</span>
            </Toolbar>
          </Box>
        </Drawer>
        
      <div
       
      >
       
      </div>
    </>

    
  );
}
