import Head from "next/head";
import Image from "next/image";
import { AppBar, Box, Drawer, ListItemIcon, ListItemText, MenuItem, MenuList, ThemeProvider, Toolbar, Typography } from "@mui/material";
import sanctuaryTheme from "@/styles/sanctuaryTheme";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { supabase } from '@/lib/supabaseClient';

// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
import { getDatabase, ref, set } from "firebase/database";
import { getAnalytics } from "firebase/analytics";
import {getAuth, getRedirectResult, signInWithPopup, signInWithRedirect} from "firebase/auth";
import { GoogleAuthProvider } from "firebase/auth";

import { app } from "@/utils/firebaseConfig"; // Ensure this path points to your Firebase configuration file


import HistoryEduIcon from '@mui/icons-material/HistoryEdu';
import SanctuaryMenu from "@/components/layout/SanctuaryMenu";




export default function Home() {
  const router = useRouter();
  const user = getAuth(app).currentUser;

  const [authenticated, setAuthenticated] = useState(false);
  
  

  useEffect(() => {
    
    const checkAuth = async () => {
      console.log(getAuth(app).currentUser);
      console.log(user);
      if (!user) {
        router.push('/login'); // Redirect to login if not authenticated
      } else {
        setAuthenticated(true);
      }
    };
    checkAuth();
  }, [router]);

  if (!authenticated) return null; // Prevent rendering until authentication is checked

  return (
<>
      <Head>
        <title>Sanctuary App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <SanctuaryMenu />
        
    
    </>

    
  );
}
