//page for individual sermon

import SanctuaryMenu from "@/components/layout/SanctuaryMenu";
import { getSermonById } from "@/utils/firebaseConfig";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Markdown from 'react-markdown';

export default function SermonPage() {
  const router = useRouter();
  const { sermon_id } = router.query;
  const [sermon, setSermon] = useState<any>(null); // Initialize sermon state

  useEffect(() => {
    if (!sermon_id) {
      router.push("/sermons"); // Redirect to sermons list if sermon_id is not present
    }else{
        getSermonById(sermon_id as string).then((e) => {
            console.log(e);
            setSermon(e);
            if(e == null) return;
        });
    }
  }, [sermon_id, router]);  

  return(
    <>
    <Head>
            <title>Sanctuary App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          
          <SanctuaryMenu />
          <div className="sermon-page" style={{ marginLeft: '240px', padding: '20px' }}>
            {sermon ? (
            <div>
                <h1>{sermon.title}</h1>
                <p>{sermon.scripture}</p>
                <h2>Outline</h2>
                <ul>
                {sermon.sermon_outline.map((point: string, index: number) => (
                    <li key={index}>{point}</li>
                ))}
                </ul>
                <h2>Key Takeaways</h2>
                <ul>
                {sermon.key_takeaways.map((takeaway: string, index: number) => (
                    <li key={index}>{takeaway}</li>
                ))}
                </ul>
                <h2>Sermon Body</h2>
                <Markdown>{sermon.sermon_body}</Markdown>
            </div>
            ) : (
            <p>Loading...</p>
            )}
        </div>
    </>
  )
}